import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

const templateRoot = new URL("../", import.meta.url);

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", {
      headers: { accept: "text/html" },
    }),
    {
      ASSETS: {
        fetch: async () => new Response("Not found", { status: 404 }),
      },
    },
    {
      waitUntil() {},
      passThroughOnException() {},
    },
  );
}

test("server-renders the CodeFlow Inspector workbench shell", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>CodeFlow Inspector<\/title>/i);
  assert.match(html, /CodeFlow Inspector/);
  assert.match(html, /当前项目解析概览/);
  assert.match(html, /项目中心/);
  assert.match(html, /导航样式/);
  assert.match(html, /项目数据、图谱、断点与诊断独立保存/);
  assert.match(html, /本地知识/);
  assert.match(html, /文件页/);
  assert.match(html, /模块页/);
  assert.match(html, /项目数据路径/);
  assert.match(html, /分析报告/);
  assert.match(html, /项目完整分析报告/);
  assert.match(html, /水流法/);
  assert.match(html, /函数水流图/);
  assert.match(html, /函数水流图统计/);
  assert.match(html, /诊断提示/);
  const watershedToolbarIndex = html.indexOf("watershed-toolbar");
  const watershedCanvasIndex = html.indexOf("watershed-map-shell");
  assert.ok(watershedToolbarIndex >= 0 && watershedCanvasIndex >= 0);
  assert.ok(watershedToolbarIndex < watershedCanvasIndex, "graph controls must render above, not inside, the scrollable canvas");
  assert.match(html, /函数解析/);
  assert.match(html, /分析内核/);
  assert.match(html, /本地解析层/);
  assert.match(html, /本地库体检/);
  assert.match(html, /规则覆盖自检/);
  assert.match(html, /仍需补漏/);
  assert.match(html, /知识库\/数据底座/);
  assert.match(html, /计算机数学基础库/);
  assert.match(html, /语言生态库/);
  assert.match(html, /本地函数图索引/);
  assert.match(html, /Code Flow 本地数据库/);
  assert.match(html, /深层种子/);
  assert.match(html, /knowledge_rules/);
  assert.match(html, /source_versions/);
  assert.match(html, /language_apis/);
  assert.match(html, /rule_matches/);
  assert.match(html, /version_constraints/);
  assert.match(html, /fault_samples/);
  assert.match(html, /benchmark_profiles/);
  assert.match(html, /library_domains/);
  assert.match(html, /library_entries/);
  assert.match(html, /成熟本地库/);
  assert.match(html, /DeepWeb 神经数据库/);
  assert.match(html, /专家监督学习闭环/);
  assert.match(html, /自监督候选层/);
  assert.match(html, /老师标签/);
  assert.match(html, /监督命中/);
  assert.match(html, /防错护栏/);
  assert.match(html, /基因进化层/);
  assert.match(html, /错误信号/);
  assert.match(html, /fitness/);
  assert.match(html, /知识 -/);
  assert.match(html, /隔离样本/);
  assert.match(html, /老师冲突/);
  assert.match(html, /类别中心/);
  assert.match(html, /对比样本/);
  assert.match(html, /推理运行/);
  assert.match(html, /多维特征/);
  assert.match(html, /DeepWeb 证据质量/);
  assert.match(html, /成熟验证/);
  assert.match(html, /验证场景/);
  assert.match(html, /验证证据/);
  assert.match(html, /极限测试优化/);
  assert.match(html, /优化门槛/);
  assert.match(html, /监督浇灌迭代/);
  assert.match(html, /浇灌稳定门/);
  assert.match(html, /吸收证据/);
  assert.match(html, /DeepWeb 回放记忆库/);
  assert.match(html, /回放准备/);
  assert.match(html, /退化风险/);
  assert.match(html, /SQLite-ready 本地同步/);
  assert.match(html, /sql\.js\/OPFS SQLite 查询库/);
  assert.match(html, /导出 SQLite 数据库/);
  assert.match(html, /清空 SQLite 文件/);
  assert.match(html, /Native SQLite 桌面写入器/);
  assert.match(html, /清空 native SQLite/);
  assert.match(html, /待同步/);
  assert.match(html, /IndexedDB 持久化引擎/);
  assert.match(html, /导出持久化快照/);
  assert.match(html, /导入持久化快照/);
  assert.match(html, /场景通过/);
  assert.match(html, /deepweb_feature_spaces/);
  assert.match(html, /deepweb_feature_vectors/);
  assert.match(html, /deepweb_language_adapters/);
  assert.match(html, /deepweb_validation_scenarios/);
  assert.match(html, /deepweb_validation_evidence/);
  assert.match(html, /deepweb_extreme_test_runs/);
  assert.match(html, /database_optimization_profiles/);
  assert.match(html, /deepweb_irrigation_runs/);
  assert.match(html, /deepweb_irrigation_evidence/);
  assert.match(html, /deepweb_irrigation_epochs/);
  assert.match(html, /deepweb_weight_update_events/);
  assert.match(html, /deepweb_replay_memory_snapshots/);
  assert.match(html, /deepweb_replay_comparisons/);
  assert.match(html, /deepweb_replay_promotion_decisions/);
  assert.match(html, /deepweb_local_sqlite_journal/);
  assert.match(html, /deepweb_local_storage_engines/);
  assert.match(html, /deepweb_local_snapshot_exports/);
  assert.match(html, /deepweb_supervision_labels/);
  assert.match(html, /deepweb_teacher_reliability/);
  assert.match(html, /deepweb_quarantined_labels/);
  assert.match(html, /deepweb_error_signals/);
  assert.match(html, /deepweb_label_centroids/);
  assert.match(html, /deepweb_contrastive_pairs/);
  assert.match(html, /deepweb_self_supervised_epochs/);
  assert.match(html, /deepweb_supervised_epochs/);
  assert.match(html, /deepweb_rollback_snapshots/);
  assert.match(html, /deepweb_gene_pool/);
  assert.match(html, /deepweb_genome_generations/);
  assert.match(html, /deepweb_gene_expression/);
  assert.match(html, /deepweb_fitness_scores/);
  assert.match(html, /deepweb_inference_runs/);
  assert.match(html, /本地规则命中/);
  assert.match(html, /Runtime Lab/);
  assert.match(html, /Static Dry-run/);
  assert.match(html, /Program Digital Twin/);
  assert.match(html, /孪生实验/);
  assert.match(html, /模型仿真/);
  assert.match(html, /静态推断/);
  assert.match(html, /沙箱候选与模拟结果/);
  assert.match(html, /导出 PDF/);
  assert.match(html, /主控代码树与执行轨迹/);
  assert.match(html, /选择建议 → 生成 Diff → 项目副本 A\/B → 审批写回/);
  assert.match(html, /Tauri 受控运行器/);
  assert.match(html, /执行当前项目/);
  assert.match(html, /临时项目副本/);
  assert.match(html, /不接受任意 shell 命令/);
  assert.match(html, /Compiler API/);
  assert.match(html, /地图可读性/);
  assert.match(html, /水流法主控模型/);
  assert.match(html, /汇聚与分支节点/);
  assert.match(html, /用虚拟地形组织从输入到输出的数据路径/);
  assert.match(html, /项目与文件解析/);
  assert.match(html, /v1 完整/);
  assert.match(html, /结构覆盖/);
  assert.match(html, /技术说明/);
  assert.match(html, /功能解读/);
  assert.match(html, /文件职责清单/);
  assert.match(html, /候选解释/);
  assert.match(html, /设计反推报告/);
  assert.match(html, /设计意图/);
  assert.match(html, /架构与模块协作/);
  assert.match(html, /反推结论与待确认事项/);
  assert.match(html, /功能模块清单/);
  assert.match(html, /函数职责详解/);
  assert.match(html, /完整主流程/);
  assert.match(html, /证据来源/);
  assert.match(html, /分析内核职责/);
  assert.match(html, /安全检查/);
  assert.match(html, /诊断证据完整度/);
  assert.match(html, /哪些结论还不能确认/);
  assert.match(html, /程序数字孪生/);
  assert.match(html, /其他项目的数据、图谱和诊断保持隔离/);
  assert.doesNotMatch(html, /codex-preview|react-loading-skeleton|Your site is taking shape/i);
});

test("keeps starter preview code removed", async () => {
  const [
    page,
    waterDiagram,
    flowEngine,
    localParser,
    tsParser,
    layout,
    packageJson,
    dbSchema,
    knowledgeRules,
    localGraphIndex,
    localRuleEngine,
    coverageAudit,
    deepKnowledgeDb,
    matureLocalLibrary,
    deepWebNeuralDb,
    deepWebMemoryStore,
    deepWebSqliteJournal,
    deepWebIndexedDbStore,
    deepWebOpfsSqliteStore,
    nativeSqliteWriter,
    workspaceFiles,
    workspaceProjectStore,
    tauriConfig,
    tauriCargo,
    tauriLib,
  ] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/WaterCanalDiagram.tsx", import.meta.url), "utf8"),
    readFile(new URL("../src/lib/flow/flow-engine.ts", import.meta.url), "utf8"),
    readFile(new URL("../src/lib/parser/local-parser.ts", import.meta.url), "utf8"),
    readFile(new URL("../src/lib/parser/typescript-parser.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
    readFile(new URL("../db/schema.ts", import.meta.url), "utf8"),
    readFile(new URL("../src/lib/library/local-knowledge-rules.ts", import.meta.url), "utf8"),
    readFile(new URL("../src/lib/index/local-graph-index.ts", import.meta.url), "utf8"),
    readFile(new URL("../src/lib/rules/local-rule-engine.ts", import.meta.url), "utf8"),
    readFile(new URL("../src/lib/library/knowledge-coverage-audit.ts", import.meta.url), "utf8"),
    readFile(new URL("../src/lib/library/deep-knowledge-database.ts", import.meta.url), "utf8"),
    readFile(new URL("../src/lib/library/mature-local-library.ts", import.meta.url), "utf8"),
    readFile(new URL("../src/lib/library/deepweb-neural-database.ts", import.meta.url), "utf8"),
    readFile(new URL("../src/lib/memory/deepweb-memory-store.ts", import.meta.url), "utf8"),
    readFile(new URL("../src/lib/persistence/deepweb-sqlite-journal.ts", import.meta.url), "utf8"),
    readFile(new URL("../src/lib/persistence/deepweb-indexeddb-store.ts", import.meta.url), "utf8"),
    readFile(new URL("../src/lib/persistence/deepweb-opfs-sqlite-store.ts", import.meta.url), "utf8"),
    readFile(new URL("../src/lib/persistence/native-sqlite-writer.ts", import.meta.url), "utf8"),
    readFile(new URL("../src/lib/workspace/files.ts", import.meta.url), "utf8"),
    readFile(new URL("../src/lib/workspace/project-store.ts", import.meta.url), "utf8"),
    readFile(new URL("../src-tauri/tauri.conf.json", import.meta.url), "utf8"),
    readFile(new URL("../src-tauri/Cargo.toml", import.meta.url), "utf8"),
    readFile(new URL("../src-tauri/src/lib.rs", import.meta.url), "utf8"),
  ]);

  assert.match(page, /parseWorkspace/);
  assert.match(page, /analyzeWorkspace/);
  assert.match(page, /WaterCanalDiagram/);
  assert.match(page, /LogicInventoryPanel/);
  assert.match(page, /水流法完整性/);
  assert.match(page, /buildTrace/);
  assert.match(page, /flowEdges/);
  assert.match(page, /ParserAdapter|parseResult/);
  assert.match(page, /localLibraryAudit/);
  assert.match(page, /dataScope/);
  assert.match(page, /library-coverage/);
  assert.match(page, /semanticIndex/);
  assert.match(page, /semanticIndex\.deepDatabase/);
  assert.match(page, /semanticIndex\.deepDatabase\.deepWeb/);
  assert.match(page, /buildWaterDeepWebBindings/);
  assert.match(page, /buildDeepWebBinding/);
  assert.match(page, /deepWebBindings/);
  assert.match(page, /confidenceImpact/);
  assert.match(page, /knowledgeScoreImpact/);
  assert.match(page, /fitnessImpact/);
  assert.match(page, /Code Flow 本地数据库/);
  assert.match(page, /DeepWeb 神经数据库/);
  assert.match(page, /maturityStageClass/);
  assert.match(page, /deepweb-maturity-grid/);
  assert.match(page, /validationScenarios/);
  assert.match(page, /validationEvidence/);
  assert.match(page, /extremeTests/);
  assert.match(page, /optimizationScore/);
  assert.match(page, /irrigationScore/);
  assert.match(page, /irrigation\.batches/);
  assert.match(page, /irrigation\.epochs/);
  assert.match(page, /irrigation\.weightDeltas/);
  assert.match(page, /currentReplaySnapshot/);
  assert.match(page, /replayMemoryReport/);
  assert.match(page, /useSyncExternalStore/);
  assert.match(page, /subscribeDeepWebReplayMemory/);
  assert.match(page, /getDeepWebReplaySnapshotPayload/);
  assert.match(page, /saveDeepWebReplaySnapshot/);
  assert.match(page, /sqliteJournalReport/);
  assert.match(page, /syncDeepWebSqliteJournal/);
  assert.match(page, /subscribeDeepWebSqliteJournal/);
  assert.match(page, /indexedDbReport/);
  assert.match(page, /syncDeepWebIndexedDbJournal/);
  assert.match(page, /opfsSqliteReport/);
  assert.match(page, /syncDeepWebOpfsSqliteDatabase/);
  assert.match(page, /exportDeepWebOpfsSqliteDatabase/);
  assert.match(page, /clearDeepWebOpfsSqliteDatabase/);
  assert.match(page, /downloadBinaryFile/);
  assert.match(page, /syncNativeSqliteWriters/);
  assert.match(page, /buildNativeCodeIndexSqliteRows/);
  assert.match(page, /nativeSqliteReport/);
  assert.match(page, /clearNativeSqliteDatabase/);
  assert.match(page, /clearDeepWebIndexedDbJournal/);
  assert.match(page, /exportDeepWebIndexedDbSnapshot/);
  assert.match(page, /importDeepWebIndexedDbSnapshot/);
  assert.match(page, /importIndexedDbSnapshot/);
  assert.match(page, /indexedDbExportMessage/);
  assert.match(page, /downloadTextFile/);
  assert.match(page, /selfSupervised/);
  assert.match(page, /generatedVectors/);
  assert.match(page, /inferenceRuns/);
  assert.match(page, /runtimeSandbox/);
  assert.match(page, /hydrologyModel/);
  assert.match(page, /knowledgeRuleReport/);
  assert.match(page, /knowledgeRuleCoverage/);
  assert.match(page, /本地规则命中/);
  assert.match(page, /规则覆盖自检/);
  assert.match(page, /rule-evolution-grid/);
  assert.match(page, /analysis\.knowledgeRuleCoverage\.evolution/);
  assert.match(page, /水流法主控模型/);
  assert.match(page, /汇聚与分支节点/);
  assert.match(page, /capabilities/);
  assert.match(page, /workspacePages/);
  assert.match(page, /WorkspaceProject/);
  assert.match(page, /activeProjectId/);
  assert.match(page, /createWorkspaceProject/);
  assert.match(page, /projectBreakpoints/);
  assert.match(page, /projectStoreReport/);
  assert.match(page, /loadWorkspaceProjectStore/);
  assert.match(page, /saveWorkspaceProjectStore/);
  assert.match(page, /buildSoftwareInterpretation/);
  assert.match(page, /buildSoftwareDesignReport/);
  assert.match(page, /buildAlgorithmDesignNarrative/);
  assert.match(page, /buildSoftwareModules/);
  assert.match(page, /buildSoftwareFunctionInsight/);
  assert.match(page, /buildSoftwareMainFlow/);
  assert.match(page, /buildSoftwareEvidenceSources/);
  assert.match(page, /softwareInterpretation/);
  assert.match(page, /software-parse-grid/);
  assert.match(page, /software-report-list/);
  assert.match(page, /software-module-list/);
  assert.match(page, /software-function-list/);
  assert.match(page, /software-flow-list/);
  assert.match(page, /humanizeHydrologyStage/);
  assert.match(page, /map-focused/);
  assert.match(localParser, /Compiler API/);
  assert.match(tsParser, /TypeScriptSyntaxScanner/);
  assert.match(page, /mapQuality/);
  assert.match(waterDiagram, /watershed-popup/);
  assert.match(waterDiagram, /watershed-edge-popup/);
  assert.match(waterDiagram, /network-hit-zone/);
  assert.match(waterDiagram, /water-edge-hit/);
  assert.match(waterDiagram, /node-diagnostic-marker/);
  assert.match(waterDiagram, /edge-diagnostic-marker/);
  assert.match(waterDiagram, /mapViewHeight/);
  assert.match(waterDiagram, /watershed-controls/);
  assert.match(waterDiagram, /scaleNodePositions/);
  assert.match(waterDiagram, /balanceNodeGrid/);
  assert.match(waterDiagram, /orderTerrainLayers/);
  assert.match(waterDiagram, /buildTerrainRoutes/);
  assert.match(waterDiagram, /panState/);
  assert.match(waterDiagram, /buildConfluenceLayout/);
  assert.match(waterDiagram, /ConfluencePoint/);
  assert.match(waterDiagram, /BifurcationPoint/);
  assert.match(waterDiagram, /ConfluenceStem/);
  assert.match(waterDiagram, /water-confluence-stem/);
  assert.match(waterDiagram, /node-flow-badge/);
  assert.match(waterDiagram, /edgeMarkerUrl/);
  assert.match(waterDiagram, /nodeRuleBindingSummary/);
  assert.match(waterDiagram, /WaterDeepWebBinding/);
  assert.match(waterDiagram, /DeepWebBindingPanel/);
  assert.match(waterDiagram, /popup-deepweb-binding/);
  assert.match(waterDiagram, /DeepWeb 主结论/);
  assert.match(waterDiagram, /deepweb-action-card/);
  assert.match(waterDiagram, /先修/);
  assert.match(waterDiagram, /deepweb-evidence-details/);
  assert.match(waterDiagram, /规则共识/);
  assert.match(waterDiagram, /buildDeepWebRuleProfile/);
  assert.match(waterDiagram, /deepWebReadableEvidenceLines/);
  assert.match(waterDiagram, /formatTechnicalLine/);
  assert.match(waterDiagram, /分析维度/);
  assert.match(waterDiagram, /代码位置/);
  assert.match(waterDiagram, /代码错误解析：/);
  assert.match(waterDiagram, /deepWebImpactText/);
  assert.match(waterDiagram, /bindingDiagnosticLevel/);
  assert.match(waterDiagram, /规则联动/);
  assert.match(waterDiagram, /edge-confluence/);
  assert.match(waterDiagram, /filterEdges/);
  assert.match(waterDiagram, /setSpacingPercent/);
  assert.match(waterDiagram, /setZoomPercent/);
  assert.match(waterDiagram, /代码错误解析/);
  assert.match(waterDiagram, /上游调用/);
  assert.match(waterDiagram, /建议代码/);
  assert.doesNotMatch(waterDiagram, /basin-layer|network-status-dot|湖水满溢风险|缺少验证阀门/);
  assert.match(page, /data-page="diagnostics"/);
  assert.match(page, /workspacePages/);
  assert.match(flowEngine, /buildFileLaneOrder/);
  assert.match(flowEngine, /buildFunctionDepths/);
  assert.match(flowEngine, /buildHydrologyModel/);
  assert.match(flowEngine, /classifyHydrologyCodeRole/);
  assert.match(flowEngine, /orderFunctionsByDataFlow/);
  assert.match(flowEngine, /buildFunctionDiagnosticDetails/);
  assert.match(flowEngine, /buildFunctionRuleBindingDetails/);
  assert.match(flowEngine, /edgeEvidenceForNodes/);
  assert.match(flowEngine, /dam-unvalidated-input/);
  assert.match(flowEngine, /evaluateKnowledgeRules/);
  assert.match(flowEngine, /applyKnowledgeRuleMatches/);
  assert.match(flowEngine, /buildKnowledgeRuleIssues/);
  assert.match(flowEngine, /knowledgeRuleCountByLibraryCategory/);
  assert.match(flowEngine, /matureLibraryAuditByCategory/);
  assert.match(flowEngine, /buildKnowledgeRuleCoverageReport/);
  assert.match(dbSchema, /sourceVersions/);
  assert.match(dbSchema, /knowledgeConcepts/);
  assert.match(dbSchema, /knowledgeRules/);
  assert.match(dbSchema, /ruleEvidence/);
  assert.match(dbSchema, /ruleMatches/);
  assert.match(dbSchema, /languageApis/);
  assert.match(dbSchema, /libraryDomains/);
  assert.match(dbSchema, /libraryEntries/);
  assert.match(dbSchema, /workspaceProjects/);
  assert.match(dbSchema, /workspaceProjectFiles/);
  assert.match(dbSchema, /workspaceProjectState/);
  assert.match(dbSchema, /workspaceProjectEvents/);
  assert.match(dbSchema, /workspaceProjectStorageEngines/);
  assert.match(dbSchema, /analysisRuns/);
  assert.match(dbSchema, /projectFiles/);
  assert.match(dbSchema, /projectFunctions/);
  assert.match(dbSchema, /functionSymbols/);
  assert.match(dbSchema, /callEdges/);
  assert.match(dbSchema, /flowNodes/);
  assert.match(dbSchema, /flowEdges/);
  assert.match(dbSchema, /dataFlowTraces/);
  assert.match(dbSchema, /debugBreakpoints/);
  assert.match(dbSchema, /knowledgeFeatureVectors/);
  assert.match(dbSchema, /deepwebFeatureSpaces/);
  assert.match(dbSchema, /deepwebModelLayers/);
  assert.match(dbSchema, /deepwebLanguageAdapters/);
  assert.match(dbSchema, /deepwebProjections/);
  assert.match(dbSchema, /deepwebFeatureVectors/);
  assert.match(dbSchema, /deepwebTrainingSamples/);
  assert.match(dbSchema, /deepwebValidationScenarios/);
  assert.match(dbSchema, /deepwebValidationEvidence/);
  assert.match(dbSchema, /deepwebExtremeTestRuns/);
  assert.match(dbSchema, /databaseOptimizationProfiles/);
  assert.match(dbSchema, /deepwebIrrigationRuns/);
  assert.match(dbSchema, /deepwebIrrigationEvidence/);
  assert.match(dbSchema, /deepwebIrrigationEpochs/);
  assert.match(dbSchema, /deepwebWeightUpdateEvents/);
  assert.match(dbSchema, /deepwebReplayMemorySnapshots/);
  assert.match(dbSchema, /deepwebReplayComparisons/);
  assert.match(dbSchema, /deepwebReplayPromotionDecisions/);
  assert.match(dbSchema, /deepwebLocalSqliteJournal/);
  assert.match(dbSchema, /deepwebLocalStorageEngines/);
  assert.match(dbSchema, /deepwebLocalSnapshotExports/);
  assert.match(dbSchema, /deepwebSupervisionLabels/);
  assert.match(dbSchema, /deepwebTeacherReliability/);
  assert.match(dbSchema, /deepwebQuarantinedLabels/);
  assert.match(dbSchema, /deepwebErrorSignals/);
  assert.match(dbSchema, /deepwebLabelCentroids/);
  assert.match(dbSchema, /deepwebContrastivePairs/);
  assert.match(dbSchema, /deepwebSelfSupervisedEpochs/);
  assert.match(dbSchema, /deepwebSupervisedEpochs/);
  assert.match(dbSchema, /deepwebRollbackSnapshots/);
  assert.match(dbSchema, /deepwebGenePool/);
  assert.match(dbSchema, /deepwebGenomeGenerations/);
  assert.match(dbSchema, /deepwebGeneExpression/);
  assert.match(dbSchema, /deepwebFitnessScores/);
  assert.match(dbSchema, /deepwebInferenceRuns/);
  assert.match(dbSchema, /versionConstraints/);
  assert.match(dbSchema, /sdkApiProfiles/);
  assert.match(dbSchema, /faultSamples/);
  assert.match(dbSchema, /benchmarkProfiles/);
  assert.match(dbSchema, /repairRecipes/);
  assert.match(dbSchema, /hardwareComponentProfiles/);
  assert.match(dbSchema, /environmentProfiles/);
  assert.match(knowledgeRules, /localKnowledgeRules/);
  assert.match(knowledgeRules, /math-reachability-closure/);
  assert.match(knowledgeRules, /algorithm-linear-scan-index/);
  assert.match(knowledgeRules, /efficiency-await-in-loop/);
  assert.match(knowledgeRules, /security-command-exec/);
  assert.match(knowledgeRules, /stability-missing-timeout/);
  assert.match(knowledgeRules, /language-api-node-exec/);
  assert.match(knowledgeRules, /security-xss-sink/);
  assert.match(knowledgeRules, /security-ssrf-request/);
  assert.match(knowledgeRules, /security-csrf-mutation/);
  assert.match(knowledgeRules, /security-cors-wildcard-credentials/);
  assert.match(knowledgeRules, /security-jwt-weak-verify/);
  assert.match(knowledgeRules, /security-dependency-vulnerability/);
  assert.match(knowledgeRules, /security-orm-raw-query/);
  assert.match(knowledgeRules, /efficiency-unbounded-promise-all/);
  assert.match(knowledgeRules, /efficiency-orm-overfetch/);
  assert.match(knowledgeRules, /stability-partial-write-transaction/);
  assert.match(knowledgeRules, /stability-lock-contention/);
  assert.match(knowledgeRules, /stability-device-offline/);
  assert.match(knowledgeRules, /stability-hardware-watchdog-missing/);
  assert.match(knowledgeRules, /language-api-python-pickle-load/);
  assert.match(knowledgeRules, /language-api-java-runtime-exec/);
  assert.match(knowledgeRules, /language-api-c-strcpy-gets/);
  assert.match(knowledgeRules, /language-api-prisma-queryraw-unsafe/);
  assert.match(knowledgeRules, /language-api-arduino-serial-read/);
  assert.match(knowledgeRules, /evidenceType: "runtime"/);
  assert.match(knowledgeRules, /evidenceType: "dependency"/);
  assert.match(localGraphIndex, /localKnowledgeRules/);
  assert.match(localGraphIndex, /source_versions/);
  assert.match(localGraphIndex, /rule_evidence/);
  assert.match(localGraphIndex, /rule_matches/);
  assert.match(localGraphIndex, /language_apis/);
  assert.match(localGraphIndex, /buildDeepKnowledgeDatabaseReport/);
  assert.match(localGraphIndex, /deepKnowledgeSeedCount/);
  assert.match(localGraphIndex, /version_constraints/);
  assert.match(localGraphIndex, /fault_samples/);
  assert.match(localGraphIndex, /benchmark_profiles/);
  assert.match(localGraphIndex, /localMatureLibraryEntries/);
  assert.match(localGraphIndex, /library_domains/);
  assert.match(localGraphIndex, /library_entries/);
  assert.match(localGraphIndex, /matureLibraryTotalCount/);
  assert.match(localGraphIndex, /buildDeepWebNeuralDatabaseReport/);
  assert.match(localGraphIndex, /deepWebSeedCount/);
  assert.match(localGraphIndex, /deepweb_feature_spaces/);
  assert.match(localGraphIndex, /deepweb_validation_scenarios/);
  assert.match(localGraphIndex, /deepweb_validation_evidence/);
  assert.match(localGraphIndex, /deepweb_extreme_test_runs/);
  assert.match(localGraphIndex, /database_optimization_profiles/);
  assert.match(localGraphIndex, /deepweb_irrigation_runs/);
  assert.match(localGraphIndex, /deepweb_irrigation_evidence/);
  assert.match(localGraphIndex, /deepweb_irrigation_epochs/);
  assert.match(localGraphIndex, /deepweb_weight_update_events/);
  assert.match(localGraphIndex, /DeepWeb 监督浇灌/);
  assert.match(localGraphIndex, /deepweb_replay_memory_snapshots/);
  assert.match(localGraphIndex, /deepweb_replay_comparisons/);
  assert.match(localGraphIndex, /deepweb_replay_promotion_decisions/);
  assert.match(localGraphIndex, /DeepWeb 回放记忆/);
  assert.match(localGraphIndex, /deepweb_local_sqlite_journal/);
  assert.match(localGraphIndex, /DeepWeb SQLite 同步日志/);
  assert.match(localGraphIndex, /deepweb_local_storage_engines/);
  assert.match(localGraphIndex, /DeepWeb 本地持久化引擎/);
  assert.match(localGraphIndex, /deepweb_local_snapshot_exports/);
  assert.match(localGraphIndex, /DeepWeb 本地快照导出/);
  assert.match(localGraphIndex, /deepweb_supervision_labels/);
  assert.match(localGraphIndex, /deepweb_teacher_reliability/);
  assert.match(localGraphIndex, /deepweb_quarantined_labels/);
  assert.match(localGraphIndex, /deepweb_error_signals/);
  assert.match(localGraphIndex, /deepweb_label_centroids/);
  assert.match(localGraphIndex, /deepweb_contrastive_pairs/);
  assert.match(localGraphIndex, /deepweb_self_supervised_epochs/);
  assert.match(localGraphIndex, /deepweb_supervised_epochs/);
  assert.match(localGraphIndex, /deepweb_rollback_snapshots/);
  assert.match(localGraphIndex, /deepweb_gene_pool/);
  assert.match(localGraphIndex, /deepweb_genome_generations/);
  assert.match(localGraphIndex, /deepweb_gene_expression/);
  assert.match(localGraphIndex, /deepweb_fitness_scores/);
  assert.match(localGraphIndex, /deepweb_inference_runs/);
  assert.match(localGraphIndex, /inferenceRunCount/);
  assert.match(deepKnowledgeDb, /localDeepKnowledgeTableCatalog/);
  assert.match(deepKnowledgeDb, /成熟知识层/);
  assert.match(deepKnowledgeDb, /DeepWeb神经层/);
  assert.match(deepKnowledgeDb, /library_domains/);
  assert.match(deepKnowledgeDb, /library_entries/);
  assert.match(deepKnowledgeDb, /deepweb_feature_spaces/);
  assert.match(deepKnowledgeDb, /deepweb_validation_scenarios/);
  assert.match(deepKnowledgeDb, /deepweb_validation_evidence/);
  assert.match(deepKnowledgeDb, /deepweb_extreme_test_runs/);
  assert.match(deepKnowledgeDb, /database_optimization_profiles/);
  assert.match(deepKnowledgeDb, /deepweb_irrigation_runs/);
  assert.match(deepKnowledgeDb, /deepweb_irrigation_evidence/);
  assert.match(deepKnowledgeDb, /deepweb_irrigation_epochs/);
  assert.match(deepKnowledgeDb, /deepweb_weight_update_events/);
  assert.match(deepKnowledgeDb, /deepweb_replay_memory_snapshots/);
  assert.match(deepKnowledgeDb, /deepweb_replay_comparisons/);
  assert.match(deepKnowledgeDb, /deepweb_replay_promotion_decisions/);
  assert.match(deepKnowledgeDb, /deepweb_local_sqlite_journal/);
  assert.match(deepKnowledgeDb, /deepweb_local_storage_engines/);
  assert.match(deepKnowledgeDb, /deepweb_local_snapshot_exports/);
  assert.match(deepKnowledgeDb, /deepweb_model_layers/);
  assert.match(deepKnowledgeDb, /deepweb_language_adapters/);
  assert.match(deepKnowledgeDb, /deepweb_projections/);
  assert.match(deepKnowledgeDb, /deepweb_feature_vectors/);
  assert.match(deepKnowledgeDb, /deepweb_training_samples/);
  assert.match(deepKnowledgeDb, /deepweb_supervision_labels/);
  assert.match(deepKnowledgeDb, /deepweb_teacher_reliability/);
  assert.match(deepKnowledgeDb, /deepweb_quarantined_labels/);
  assert.match(deepKnowledgeDb, /deepweb_error_signals/);
  assert.match(deepKnowledgeDb, /deepweb_label_centroids/);
  assert.match(deepKnowledgeDb, /deepweb_contrastive_pairs/);
  assert.match(deepKnowledgeDb, /deepweb_self_supervised_epochs/);
  assert.match(deepKnowledgeDb, /deepweb_supervised_epochs/);
  assert.match(deepKnowledgeDb, /deepweb_rollback_snapshots/);
  assert.match(deepKnowledgeDb, /deepweb_gene_pool/);
  assert.match(deepKnowledgeDb, /deepweb_genome_generations/);
  assert.match(deepKnowledgeDb, /deepweb_gene_expression/);
  assert.match(deepKnowledgeDb, /deepweb_fitness_scores/);
  assert.match(deepKnowledgeDb, /deepweb_inference_runs/);
  assert.match(deepKnowledgeDb, /localKnowledgeFeatureVectors/);
  assert.match(deepKnowledgeDb, /localVersionConstraints/);
  assert.match(deepKnowledgeDb, /localSdkApiProfiles/);
  assert.match(deepKnowledgeDb, /localFaultSamples/);
  assert.match(deepKnowledgeDb, /localBenchmarkProfiles/);
  assert.match(deepKnowledgeDb, /localRepairRecipes/);
  assert.match(deepKnowledgeDb, /localHardwareComponentProfiles/);
  assert.match(deepKnowledgeDb, /localEnvironmentProfiles/);
  assert.match(deepKnowledgeDb, /version-express-body-parser/);
  assert.match(deepKnowledgeDb, /sdk-java-jdbc-statement/);
  assert.match(deepKnowledgeDb, /fault-missing-http-timeout/);
  assert.match(deepKnowledgeDb, /bench-batch-db-writes/);
  assert.match(deepKnowledgeDb, /repair-timeout-retry-budget/);
  assert.match(deepKnowledgeDb, /hw-i2c-sensor/);
  assert.match(deepKnowledgeDb, /env-java-spring/);
  assert.match(localRuleEngine, /evaluateKnowledgeRules/);
  assert.match(localRuleEngine, /passesRuleContext/);
  assert.match(localRuleEngine, /buildKnowledgeRuleIssues/);
  assert.match(localRuleEngine, /ruleMatchesForFunction/);
  assert.match(localRuleEngine, /security-csrf-mutation/);
  assert.match(localRuleEngine, /security-orm-raw-query/);
  assert.match(localRuleEngine, /stability-device-offline/);
  assert.match(localRuleEngine, /efficiency-orm-overfetch/);
  assert.match(coverageAudit, /buildKnowledgeRuleCoverageReport/);
  assert.match(coverageAudit, /matureLibraryAuditSummary/);
  assert.match(coverageAudit, /buildKnowledgeRuleEvolution/);
  assert.match(coverageAudit, /Deep Evidence Web/);
  assert.match(coverageAudit, /版本差异缺/);
  assert.match(coverageAudit, /项目图谱 Schema/);
  assert.match(coverageAudit, /深层证据 Schema/);
  assert.match(coverageAudit, /成熟本地库 Schema/);
  assert.match(coverageAudit, /categoryTargets/);
  assert.match(coverageAudit, /缺少运行时样本证据类型/);
  assert.match(coverageAudit, /Java、C\/C\+\+、ORM、Web 框架、环境载体和硬件接口/);
  assert.match(matureLocalLibrary, /localMatureLibraryEntries/);
  assert.match(matureLocalLibrary, /localMatureLibraryTargets/);
  assert.match(matureLocalLibrary, /matureLibraryAuditByCategory/);
  assert.match(matureLocalLibrary, /matureLibraryTotalCount/);
  assert.match(matureLocalLibrary, /数学模型库/);
  assert.match(matureLocalLibrary, /安全规则库/);
  assert.match(matureLocalLibrary, /语言生态库/);
  assert.match(matureLocalLibrary, /电子元件参数库/);
  assert.match(matureLocalLibrary, /工具适配器/);
  assert.match(deepWebNeuralDb, /localDeepWebFeatureSpaces/);
  assert.match(deepWebNeuralDb, /localDeepWebModelLayers/);
  assert.match(deepWebNeuralDb, /localDeepWebLanguageAdapters/);
  assert.match(deepWebNeuralDb, /localDeepWebProjections/);
  assert.match(deepWebNeuralDb, /localDeepWebTrainingSamples/);
  assert.match(deepWebNeuralDb, /localDeepWebValidationScenarios/);
  assert.match(deepWebNeuralDb, /buildDeepWebNeuralDatabaseReport/);
  assert.match(deepWebNeuralDb, /Expert-Supervised DeepWeb/);
  assert.match(deepWebNeuralDb, /buildValidationEvidenceReports/);
  assert.match(deepWebNeuralDb, /validationEvidenceVector/);
  assert.match(deepWebNeuralDb, /labelFromValidationEvidence/);
  assert.match(deepWebNeuralDb, /localDeepWebExtremeTests/);
  assert.match(deepWebNeuralDb, /buildExtremeTestReports/);
  assert.match(deepWebNeuralDb, /buildOptimizationReport/);
  assert.match(deepWebNeuralDb, /buildIrrigationReport/);
  assert.match(deepWebNeuralDb, /buildIrrigationBatches/);
  assert.match(deepWebNeuralDb, /buildIrrigationWeightDeltas/);
  assert.match(deepWebNeuralDb, /buildIrrigationEpochs/);
  assert.match(deepWebNeuralDb, /deepweb_irrigation_runs/);
  assert.match(deepWebNeuralDb, /deepweb_weight_update_events/);
  assert.match(deepWebNeuralDb, /deepweb_replay_memory_snapshots/);
  assert.match(deepWebNeuralDb, /deepweb_local_sqlite_journal/);
  assert.match(deepWebNeuralDb, /deepweb_local_storage_engines/);
  assert.match(deepWebNeuralDb, /deepweb_local_snapshot_exports/);
  assert.match(deepWebNeuralDb, /database_stress/);
  assert.match(deepWebNeuralDb, /vector_stress/);
  assert.match(deepWebNeuralDb, /benchmark_before_after/);
  assert.match(deepWebNeuralDb, /repair_verification/);
  assert.match(deepWebNeuralDb, /buildValidationScenarioReports/);
  assert.match(deepWebNeuralDb, /buildMaturityReport/);
  assert.match(deepWebNeuralDb, /maturityBlockers/);
  assert.match(deepWebNeuralDb, /缺失/);
  assert.match(deepWebNeuralDb, /基础覆盖/);
  assert.match(deepWebNeuralDb, /成熟验证/);
  assert.match(deepWebNeuralDb, /buildExpertSupervisionLabels/);
  assert.match(deepWebNeuralDb, /buildSupervisedReport/);
  assert.match(deepWebNeuralDb, /buildTeacherDecision/);
  assert.match(deepWebNeuralDb, /buildTeacherReliability/);
  assert.match(deepWebNeuralDb, /buildQuarantine/);
  assert.match(deepWebNeuralDb, /buildRollbackSnapshot/);
  assert.match(deepWebNeuralDb, /buildErrorSignals/);
  assert.match(deepWebNeuralDb, /defaultErrorSignalImpacts/);
  assert.match(deepWebNeuralDb, /buildEvolutionReport/);
  assert.match(deepWebNeuralDb, /buildGenePool/);
  assert.match(deepWebNeuralDb, /buildGenomes/);
  assert.match(deepWebNeuralDb, /scoreGenome/);
  assert.match(deepWebNeuralDb, /mutateGenes/);
  assert.match(deepWebNeuralDb, /normalizeDimensionGenes/);
  assert.match(deepWebNeuralDb, /teacherMatchScore/);
  assert.match(deepWebNeuralDb, /quarantineReason/);
  assert.match(deepWebNeuralDb, /supervisedLoss/);
  assert.match(deepWebNeuralDb, /buildGeneratedDeepWebVectors/);
  assert.match(deepWebNeuralDb, /buildProjectFileVector/);
  assert.match(deepWebNeuralDb, /buildVersionConstraintVector/);
  assert.match(deepWebNeuralDb, /buildSdkApiVector/);
  assert.match(deepWebNeuralDb, /buildFaultSampleVector/);
  assert.match(deepWebNeuralDb, /buildBenchmarkProfileVector/);
  assert.match(deepWebNeuralDb, /buildRepairRecipeVector/);
  assert.match(deepWebNeuralDb, /buildHardwareProfileVector/);
  assert.match(deepWebNeuralDb, /buildEnvironmentProfileVector/);
  assert.match(deepWebNeuralDb, /dw-sample-version-timeout-drift/);
  assert.match(deepWebNeuralDb, /dw-vector-version-/);
  assert.match(deepWebNeuralDb, /dw-vector-hardware-/);
  assert.match(deepWebNeuralDb, /buildSelfSupervisedReport/);
  assert.match(deepWebNeuralDb, /buildContrastivePairs/);
  assert.match(deepWebNeuralDb, /buildInferenceRuns/);
  assert.match(deepWebNeuralDb, /inferPseudoLabel/);
  assert.match(deepWebNeuralDb, /weightedVectorDistance/);
  assert.match(deepWebNeuralDb, /TypeScript\/JavaScript/);
  assert.match(deepWebNeuralDb, /Python/);
  assert.match(deepWebNeuralDb, /C\/C\+\+/);
  assert.match(deepWebNeuralDb, /deepweb_feature_vectors/);
  assert.match(deepWebNeuralDb, /deepweb_supervision_labels/);
  assert.match(deepWebNeuralDb, /deepweb_teacher_reliability/);
  assert.match(deepWebNeuralDb, /deepweb_quarantined_labels/);
  assert.match(deepWebNeuralDb, /deepweb_error_signals/);
  assert.match(deepWebNeuralDb, /deepweb_label_centroids/);
  assert.match(deepWebNeuralDb, /deepweb_contrastive_pairs/);
  assert.match(deepWebNeuralDb, /deepweb_self_supervised_epochs/);
  assert.match(deepWebNeuralDb, /deepweb_supervised_epochs/);
  assert.match(deepWebNeuralDb, /deepweb_rollback_snapshots/);
  assert.match(deepWebNeuralDb, /deepweb_gene_pool/);
  assert.match(deepWebNeuralDb, /deepweb_genome_generations/);
  assert.match(deepWebNeuralDb, /deepweb_gene_expression/);
  assert.match(deepWebNeuralDb, /deepweb_fitness_scores/);
  assert.match(deepWebNeuralDb, /deepweb_inference_runs/);
  assert.match(deepWebMemoryStore, /DEEPWEB_MEMORY_STORAGE_KEY/);
  assert.match(deepWebMemoryStore, /buildDeepWebReplaySnapshot/);
  assert.match(deepWebMemoryStore, /loadDeepWebReplaySnapshots/);
  assert.match(deepWebMemoryStore, /saveDeepWebReplaySnapshot/);
  assert.match(deepWebMemoryStore, /buildDeepWebReplayMemoryReport/);
  assert.match(deepWebMemoryStore, /compareReplaySnapshots/);
  assert.match(deepWebMemoryStore, /localStorage/);
  assert.match(deepWebSqliteJournal, /DEEPWEB_SQLITE_JOURNAL_STORAGE_KEY/);
  assert.match(deepWebSqliteJournal, /buildDeepWebSqliteJournalRows/);
  assert.match(deepWebSqliteJournal, /syncDeepWebSqliteJournal/);
  assert.match(deepWebSqliteJournal, /buildDeepWebSqliteJournalReport/);
  assert.match(deepWebSqliteJournal, /INSERT OR REPLACE INTO/);
  assert.match(deepWebIndexedDbStore, /DEEPWEB_INDEXEDDB_NAME/);
  assert.match(deepWebIndexedDbStore, /DEEPWEB_INDEXEDDB_ENGINE_STORE/);
  assert.match(deepWebIndexedDbStore, /DEEPWEB_INDEXEDDB_SNAPSHOT_STORE/);
  assert.match(deepWebIndexedDbStore, /syncDeepWebIndexedDbJournal/);
  assert.match(deepWebIndexedDbStore, /exportDeepWebIndexedDbSnapshot/);
  assert.match(deepWebIndexedDbStore, /importDeepWebIndexedDbSnapshot/);
  assert.match(deepWebIndexedDbStore, /loadDeepWebIndexedDbSnapshotEvents/);
  assert.match(deepWebIndexedDbStore, /DeepWebIndexedDbSnapshot/);
  assert.match(deepWebIndexedDbStore, /openDeepWebIndexedDb/);
  assert.match(deepWebIndexedDbStore, /IndexedDB durable journal/);
  assert.match(deepWebOpfsSqliteStore, /DEEPWEB_OPFS_SQLITE_DB_FILE/);
  assert.match(deepWebOpfsSqliteStore, /DEEPWEB_SQLITE_TABLE_COUNT/);
  assert.match(deepWebOpfsSqliteStore, /syncDeepWebOpfsSqliteDatabase/);
  assert.match(deepWebOpfsSqliteStore, /exportDeepWebOpfsSqliteDatabase/);
  assert.match(deepWebOpfsSqliteStore, /clearDeepWebOpfsSqliteDatabase/);
  assert.match(deepWebOpfsSqliteStore, /initializeDeepWebSchema/);
  assert.match(deepWebOpfsSqliteStore, /CREATE TABLE IF NOT EXISTS deepweb_replay_memory_snapshots/);
  assert.match(deepWebOpfsSqliteStore, /queryPreviewSql/);
  assert.match(deepWebOpfsSqliteStore, /navigator/);
  assert.match(deepWebOpfsSqliteStore, /getDirectory/);
  assert.match(deepWebOpfsSqliteStore, /sql\.js/);
  assert.match(nativeSqliteWriter, /NATIVE_SQLITE_DB_FILE/);
  assert.match(nativeSqliteWriter, /codeflow\.sqlite3/);
  assert.match(nativeSqliteWriter, /Tauri native SQLite/);
  assert.match(nativeSqliteWriter, /buildNativeCodeIndexSqliteRows/);
  assert.match(nativeSqliteWriter, /syncNativeSqliteWriters/);
  assert.match(nativeSqliteWriter, /clearNativeSqliteDatabase/);
  assert.match(nativeSqliteWriter, /analysis_runs/);
  assert.match(nativeSqliteWriter, /project_functions/);
  assert.match(nativeSqliteWriter, /flow_edges/);
  assert.match(nativeSqliteWriter, /deepweb_local_sqlite_journal/);
  assert.match(layout, /lang=\{productLocale\}/);
  assert.match(packageJson, /"name": "code-function-visualizer"/);
  assert.match(packageJson, /"sql\.js"/);
  assert.match(packageJson, /"@tauri-apps\/cli"/);
  assert.match(packageJson, /"desktop:dev"/);
  assert.match(workspaceFiles, /extractFileImports/);
  assert.match(workspaceFiles, /extractEnvironmentRefs/);
  assert.match(workspaceFiles, /extractDeviceApiRefs/);
  assert.match(workspaceProjectStore, /WORKSPACE_PROJECT_STORE_KEY/);
  assert.match(workspaceProjectStore, /WORKSPACE_PROJECT_DB_NAME/);
  assert.match(workspaceProjectStore, /WORKSPACE_PROJECT_METADATA_STORE/);
  assert.match(workspaceProjectStore, /WORKSPACE_PROJECT_FILE_STORE/);
  assert.match(workspaceProjectStore, /WORKSPACE_PROJECT_ENGINE_STORE/);
  assert.match(workspaceProjectStore, /WorkspaceProjectStorePayload/);
  assert.match(workspaceProjectStore, /WorkspaceProjectStoreReport/);
  assert.match(workspaceProjectStore, /loadWorkspaceProjectStore/);
  assert.match(workspaceProjectStore, /saveWorkspaceProjectStore/);
  assert.match(workspaceProjectStore, /buildWorkspaceProjectSqliteRows/);
  assert.match(workspaceProjectStore, /INSERT OR REPLACE INTO/);
  assert.match(workspaceProjectStore, /indexedDB/);
  assert.match(workspaceProjectStore, /legacyBrowserStorage/);
  assert.match(tauriConfig, /withGlobalTauri/);
  assert.match(tauriConfig, /http:\/\/localhost:3000/);
  assert.match(tauriConfig, /\.\.\/dist\/client/);
  assert.match(tauriCargo, /rusqlite/);
  assert.match(tauriCargo, /tauri-build/);
  assert.match(tauriLib, /codeflow_sync_workspace_projects/);
  assert.match(tauriLib, /codeflow_sync_deepweb_journal/);
  assert.match(tauriLib, /codeflow_sync_code_index/);
  assert.match(tauriLib, /CREATE TABLE IF NOT EXISTS native_sqlite_writes/);
  assert.match(tauriLib, /validate_row/);
  assert.doesNotMatch(page, /SkeletonPreview|codex-preview/);
  assert.doesNotMatch(packageJson, /react-loading-skeleton/);

  await assert.rejects(access(new URL("app/_sites-preview/SkeletonPreview.tsx", templateRoot)));
  await access(new URL("public/sql-wasm.wasm", templateRoot));
  await access(new URL("src-tauri/icons/icon.png", templateRoot));
});
